name: Write commit info

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Write JSON file
        run: |
            cd .github/workflows
            node .
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update commit info
          commit_user_name: NWJ9PB
          commit_user_email: helodibalado@gmail.com